# Generated by Django 3.2 on 2021-12-20 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContinentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ParthershipNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='WorkWithus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=300)),
                ('upload_cv', models.FileField(upload_to='emtrics_cv/')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionDetailParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.TextField()),
                ('solution_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.solutiondetail')),
            ],
        ),
        migrations.CreateModel(
            name='CountryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('continent_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.continentlocation')),
            ],
        ),
        migrations.CreateModel(
            name='countryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='..', max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('country_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.countrylocation')),
            ],
        ),
    ]
