# Generated by Django 3.2 on 2021-12-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20211220_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutiondetail',
            name='intro_content',
            field=models.TextField(default='..'),
        ),
    ]
